name: "PR build"
run-name: "Build Pull Request #${{ github.event.pull_request.number }}"

on:
    pull_request_target:
      branches:
        - master
      types:
        - opened
        - synchronize

jobs:
  pr-build:
    runs-on: ubuntu-latest
    steps:
     - run: echo ${{github.event.pull_request.number}}
     - run: echo ${{github.event.number}}
     - run: echo ${{ github.event.head_commit.message }}
     - run: echo ${{ github.event.pull_request.head_commit.message }}
